package principal.vista.productos.modelo;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import modelo.producto.marca.Modelo;
import repositorio.dao.modelo.ModeloDaoImpl;
import modelo.producto.marca.Rodado;
import javax.swing.table.DefaultTableModel;
import principal.vista.productos.HomeMenuProductos;
import modelo.producto.marca.Marca;
import repositorio.dao.marca.MarcaDaoImpl;


/**
 *
 * @author rodri
 */

public class ListarModelo extends javax.swing.JFrame {

    private JTable modeloTable;
    private JButton listarButton, backButton;
    private JComboBox<Rodado> rodadoComboBox;  
    private JComboBox<Marca> marcaComboBox; 
    private JTextField codigoTextField; 

    public ListarModelo() {
        setTitle("Listar Modelos");
        setSize(800, 600);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);  
        setLayout(new BorderLayout(10, 10));

        JPanel titlePanel = new JPanel();
        JLabel titleLabel = new JLabel("Listar Modelos", SwingConstants.CENTER);
        titleLabel.setFont(new Font("Arial", Font.BOLD, 24));
        titlePanel.add(titleLabel);
        add(titlePanel, BorderLayout.NORTH);

        JPanel filterPanel = new JPanel(new GridLayout(4, 2, 10, 10));

        filterPanel.add(new JLabel("Código (Opcional):"));
        codigoTextField = new JTextField();
        filterPanel.add(codigoTextField);

        filterPanel.add(new JLabel("Marca (Opcional):"));
        marcaComboBox = new JComboBox<>();  
        marcaComboBox.setSelectedItem(null); 
        MarcaDaoImpl marcaDao = new MarcaDaoImpl();
        List<Marca> marcas = marcaDao.getMarcasComboBox(); 

        marcaComboBox.addItem(null); 
        for (Marca marca : marcas) {
            marcaComboBox.addItem(marca); 
        }
        filterPanel.add(marcaComboBox);

        filterPanel.add(new JLabel("Rodado (Opcional):"));
        rodadoComboBox = new JComboBox<>();
        rodadoComboBox.addItem(null);  
        for (Rodado rodado : Rodado.values()) {
            rodadoComboBox.addItem(rodado);  
        }
        filterPanel.add(rodadoComboBox);

        listarButton = new JButton("Listar");
        listarButton.addActionListener(new ListarButtonListener()); 
        filterPanel.add(listarButton);

        add(filterPanel, BorderLayout.NORTH);

        String[] columnNames = {"Código", "Marca", "Nombre", "Descripción", "Rodado"};
        modeloTable = new JTable(new Object[0][5], columnNames);
        JScrollPane scrollPane = new JScrollPane(modeloTable);
        add(scrollPane, BorderLayout.CENTER);

        JPanel buttonPanel = new JPanel(new FlowLayout());
        backButton = new JButton("Volver");
        backButton.addActionListener(e -> {
            new HomeMenuProductos().setVisible(true);
            dispose();
        });
        buttonPanel.add(backButton);

        add(buttonPanel, BorderLayout.SOUTH);
    }

    private class ListarButtonListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            String codigo = codigoTextField.getText(); 
            Marca selectedMarca = (Marca) marcaComboBox.getSelectedItem(); 
            Rodado rodado = (Rodado) rodadoComboBox.getSelectedItem();

            String marcaCodigo = null;
            if (selectedMarca != null) {
                marcaCodigo = selectedMarca.getCodigo();  
            }

            actualizarTablaModelos(codigo, marcaCodigo, rodado);
        }
    }

    private void actualizarTablaModelos(String codigo, String marcaCodigo, Rodado rodado) {
        ModeloDaoImpl modeloDao = new ModeloDaoImpl();

        List<Modelo> modelos = modeloDao.getModelos(
                codigo.isEmpty() ? null : codigo, 
                null, 
                marcaCodigo,
                rodado 
        );

        Object[][] data = new Object[modelos.size()][5];
        for (int i = 0; i < modelos.size(); i++) {
            Modelo modelo = modelos.get(i);
            data[i][0] = modelo.getCodigo();  
            data[i][1] = modelo.getMarca().getMarca();
            data[i][2] = modelo.getModelo();
            data[i][3] = modelo.getDescripcion();
            data[i][4] = modelo.getRodado();
        }

        modeloTable.setModel(new DefaultTableModel(
                data,
                new String[]{"Código", "Marca", "Nombre", "Descripción", "Rodado"}
        ));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarModelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarModelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarModelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarModelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarModelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
