package principal.vista.productos.categoria;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import principal.vista.productos.HomeMenuProductos;
import modelo.producto.Categoria;
import modelo.producto.TipoCategoria;
import repositorio.dao.categoria.CategoriaDaoImpl;

/**
 *
 * @author rodri
 */

public class AltaCategoria extends javax.swing.JFrame {

    private JTextField nombreCategoriaField;
    private JComboBox<String> tipoCategoriaComboBox;

    public AltaCategoria() {
        setTitle("Alta Categoría");
        setSize(400, 250);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(new GridLayout(4, 2, 10, 10));

        add(new JLabel("Tipo de Categoría:"));
        tipoCategoriaComboBox = new JComboBox<>(new String[]{"BICICLETA", "ACCESORIO", "REPUESTO"});
        add(tipoCategoriaComboBox);

        add(new JLabel("Nombre de la Categoría:"));
        nombreCategoriaField = new JTextField();
        add(nombreCategoriaField);

        JButton submitButton = new JButton("Dar de alta");
        submitButton.addActionListener(new SubmitButtonListener());
        add(submitButton);

        JButton backButton = new JButton("Volver");
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new HomeMenuProductos().setVisible(true);
                dispose();
            }
        });
        add(backButton);
    }

    private class SubmitButtonListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                String nombreCategoria = nombreCategoriaField.getText();
                String tipoCategoria = (String) tipoCategoriaComboBox.getSelectedItem();

                if (nombreCategoria.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "El nombre de la categoría no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                TipoCategoria tipo = null;
                if (tipoCategoria.equals("BICICLETA")) {
                    tipo = TipoCategoria.BICICLETA;
                } else if (tipoCategoria.equals("ACCESORIO")) {
                    tipo = TipoCategoria.ACCESORIO;
                } else if (tipoCategoria.equals("REPUESTO")) {
                    tipo = TipoCategoria.RESPUESTO;
                }

                Categoria categoria = new Categoria(nombreCategoria, tipo);

                CategoriaDaoImpl categoriaDao = new CategoriaDaoImpl();
                categoriaDao.insertarNuevaCategoria(categoria); // Aquí se usa el método insertarNuevaCategoria

                JOptionPane.showMessageDialog(null, "Categoría dada de alta exitosamente.");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
