package principal.vista.pedido;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import repositorio.dao.pedido.PedidoDaoImpl;
import modelo.pedido.Pedido;

/**
 *
 * @author rodri
 */

public class BajaPedido extends javax.swing.JFrame {

    private JTextField busquedaTextField;
    private JTable tablaPedidos;
    private JButton eliminarButton;

    public BajaPedido() {
        inicializarComponentes();
    }

    private void inicializarComponentes() {
        setTitle("Baja de Pedidos");
        setSize(800, 600);
        setLayout(new BorderLayout());

        JPanel filtrosPanel = new JPanel(new GridLayout(1, 2, 10, 10));
        filtrosPanel.setBorder(BorderFactory.createTitledBorder("Filtros de Búsqueda"));

        JLabel busquedaLabel = new JLabel("Buscar por código o estado:");
        busquedaTextField = new JTextField();

        filtrosPanel.add(busquedaLabel);
        filtrosPanel.add(busquedaTextField);

        JPanel buscarPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        JButton buscarButton = new JButton("Buscar");
        buscarButton.addActionListener(this::buscarPedidos);
        buscarButton.setPreferredSize(new Dimension(100, 30));
        buscarPanel.add(buscarButton);

        eliminarButton = new JButton("Eliminar");
        eliminarButton.setEnabled(false);
        eliminarButton.addActionListener(this::eliminarPedido);

        JPanel bottomPanel = new JPanel(new FlowLayout());
        bottomPanel.add(eliminarButton);

        tablaPedidos = new JTable(new DefaultTableModel(
                new Object[][]{},
                new String[]{"Código", "Fecha", "Vendedor", "Cliente", "Estado", "Total"}
        ));
        JScrollPane tablaScroll = new JScrollPane(tablaPedidos);

        JPanel panelBusqueda = new JPanel();
        panelBusqueda.setLayout(new BoxLayout(panelBusqueda, BoxLayout.Y_AXIS));
        panelBusqueda.add(filtrosPanel);
        panelBusqueda.add(buscarPanel);

        add(panelBusqueda, BorderLayout.NORTH);
        add(tablaScroll, BorderLayout.CENTER);
        add(bottomPanel, BorderLayout.SOUTH);

        tablaPedidos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (tablaPedidos.getSelectedRow() != -1) {
                    eliminarButton.setEnabled(true);
                }
            }
        });
    }

    private void buscarPedidos(ActionEvent event) {
        String busqueda = busquedaTextField.getText().trim();

        PedidoDaoImpl CrudPedido = new PedidoDaoImpl();
        List<Pedido> pedidos = CrudPedido.obtenerPedidos(busqueda, null, null, null, null, null, null);

        // Limpiar la tabla antes de agregar nuevas filas
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaPedidos.getModel();
        modeloTabla.setRowCount(0); // Esto limpia la tabla

        // Agregar los pedidos a la tabla
        for (Pedido pedido : pedidos) {
            modeloTabla.addRow(new Object[]{
                pedido.getCodigo(),
                pedido.getFecha(),
                pedido.getCodigoVendedor(),
                pedido.getCodigoCliente(),
                pedido.getEstado(),
                pedido.getTotalPedido()
            });
        }
    }

    private void eliminarPedido(ActionEvent event) {
        int filaSeleccionada = tablaPedidos.getSelectedRow();
        if (filaSeleccionada != -1) {
            String codigoPedido = (String) tablaPedidos.getValueAt(filaSeleccionada, 0);

            PedidoDaoImpl CrudPedido = new PedidoDaoImpl();
            CrudPedido.eliminarPedido(codigoPedido);

            JOptionPane.showMessageDialog(this, "Pedido eliminado exitosamente.");
            buscarPedidos(event);
            eliminarButton.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BajaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BajaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BajaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BajaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BajaPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
