package principal.vista.pedido;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author rodri
 */

public class HomeMenuPedidos extends javax.swing.JFrame {

    private JPanel optionsPanel;

    /**
     * Creates new form PrincipalPedido
     */
    public HomeMenuPedidos() {
        setTitle("Pedidos Menu");
        setSize(500, 400);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        // Creamos el JMenuBar
        JMenuBar menuBar = new JMenuBar();

        // Creamos los menús
        JMenu pedidosMenu = new JMenu("Pedidos");

        // Agregamos el menú al JMenuBar
        menuBar.add(pedidosMenu);

        // Agregamos el JMenuBar a la ventana
        setJMenuBar(menuBar);

        // Creamos las opciones de menú
        JMenuItem altaPedido = new JMenuItem("Alta Pedido");
        JMenuItem bajaPedido = new JMenuItem("Baja Pedido");
        JMenuItem editarPedido = new JMenuItem("Editar Pedido");
        JMenuItem consultarPedido = new JMenuItem("Listar Pedido");

        // Agregamos las opciones al menú de Pedidos
        pedidosMenu.add(altaPedido);
        pedidosMenu.add(bajaPedido);
        pedidosMenu.add(editarPedido);
        pedidosMenu.add(consultarPedido);

        // Panel central
        optionsPanel = new JPanel();
        optionsPanel.setLayout(new GridLayout(4, 1));

        add(optionsPanel, BorderLayout.CENTER);

        // Acción para la opción Alta Pedido
        altaPedido.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new AltaPedido().setVisible(true);  // Abre la ventana para alta de pedido
                dispose();  // Cierra el menú principal de Pedidos
            }
        });

        // Acción para la opción Baja Pedido
        bajaPedido.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new BajaPedido().setVisible(true);  // Abre la ventana para baja de pedido
                dispose();  // Cierra el menú principal de Pedidos
            }
        });

        // Acción para la opción Editar Pedido
        editarPedido.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new EditarPedido().setVisible(true);  // Abre la ventana para editar pedido
                dispose();  // Cierra el menú principal de Pedidos
            }
        });

        // Acción para la opción Listar Pedido
        consultarPedido.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new ListarPedido().setVisible(true);  // Abre la ventana para consultar pedido
                dispose();  // Cierra el menú principal de Pedidos
            }
        });
    }

    private class MenuActionListener implements ActionListener {

        private String option;

        public MenuActionListener(String option) {
            this.option = option;
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            showOptions(option);
        }
    }

    private void showOptions(String option) {
        optionsPanel.removeAll();

        JLabel titleLabel = new JLabel("Opciones para " + option, SwingConstants.CENTER);
        optionsPanel.add(titleLabel);

        optionsPanel.revalidate();
        optionsPanel.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeMenuPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeMenuPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeMenuPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeMenuPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeMenuPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
