package principal;

import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import javax.swing.*; 
import java.awt.event.ActionEvent; 
import java.awt.event.ActionListener;
import java.awt.*;
import principal.vista.gente.HomeMenuGente;
import principal.vista.pedido.HomeMenuPedidos;
import principal.vista.productos.HomeMenuProductos;

/**
 *
 * @author rodri
 */

public class HomeMenu extends javax.swing.JFrame{

    public HomeMenu() {
        setTitle("Mi Bicicleteria");
        setSize(400, 300);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        JPanel titlePanel = new JPanel(new GridBagLayout());
        JLabel titleLabel = new JLabel("Mi Bicicleteria", SwingConstants.CENTER);
        titleLabel.setFont(new Font("Arial", Font.BOLD, 20));
        titlePanel.add(titleLabel);

        JPanel buttonPanel = new JPanel();
        buttonPanel.setLayout(new GridLayout(1, 4, 10, 10));

        ImageIcon homeIcon = new ImageIcon(getClass().getResource("/icons/home.png"));
        ImageIcon genteIcon = new ImageIcon(getClass().getResource("/icons/gente.png"));
        ImageIcon productosIcon = new ImageIcon(getClass().getResource("/icons/productos.png"));
        ImageIcon pedidosIcon = new ImageIcon(getClass().getResource("/icons/pedidos.png"));

        int iconSize = 24;
        homeIcon = new ImageIcon(homeIcon.getImage().getScaledInstance(iconSize, iconSize, Image.SCALE_SMOOTH));
        genteIcon = new ImageIcon(genteIcon.getImage().getScaledInstance(iconSize, iconSize, Image.SCALE_SMOOTH));
        productosIcon = new ImageIcon(productosIcon.getImage().getScaledInstance(iconSize, iconSize, Image.SCALE_SMOOTH));
        pedidosIcon = new ImageIcon(pedidosIcon.getImage().getScaledInstance(iconSize, iconSize, Image.SCALE_SMOOTH));

        JButton homeButton = new JButton("Home", homeIcon);
        JButton genteButton = new JButton("Gente", genteIcon);
        JButton productosButton = new JButton("Productos", productosIcon);
        JButton pedidosButton = new JButton("Pedidos", pedidosIcon);

        genteButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new HomeMenuGente().setVisible(true);
                dispose();
            }
        });

        productosButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new HomeMenuProductos().setVisible(true);
                dispose();
            }
        });

        pedidosButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new HomeMenuPedidos().setVisible(true);
                dispose();
            }
        });

        // Agregar los botones al panel
        buttonPanel.add(homeButton);
        buttonPanel.add(genteButton);
        buttonPanel.add(productosButton);
        buttonPanel.add(pedidosButton);

        // Agregar los paneles al JFrame
        add(titlePanel, BorderLayout.CENTER);
        add(buttonPanel, BorderLayout.SOUTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
